services:
  - type: web
    name: sveltekit-console
    runtime: docker
    dockerfilePath: console/Dockerfile
    dockerContext: console
    port: 7860
    envVars:
      - key: PORT
        value: 7860
      - key: SVELTE_PORT
        value: 3000
